version: "3.7"

services:
  database-gift-card:
    image: mysql
    container_name: olist-gift-card-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=olist
      - MYSQL_DB=olist-gift-card-db
    volumes:
      - gift-card-data:/data/mysql
    networks:
      - gift-card

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  #   restart: always

  app:
    build: .
    container_name: gift-card-app
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ./:/usr/app
    networks:
      - gift-card
    links:
      - database-gift-card
    depends_on:
      - database-gift-card

volumes:
  gift-card-data:
    driver: local

networks:
  gift-card:
    driver: "bridge"
